### ISSUE TITLE
add cache

### ISSUE THREAD

**Issue by aadog** [techknowlogick/xgo#178] opened 2022-11-04 14:19 UTC
add cache

**Comment by techknowlogick** [comment] 2022-11-04 14:26
Hi @aadog, thank you for this issue. Could you describe what you are expecting if this ticket would be implemented?

**Comment by aadog** [comment] 2022-11-04 14:33
This package is redownloaded every time, the dependency problem is a cache problem, same as https://github.com/techknowlogick/xgo/pull/116, but don't know why he is not removed?

**Comment by aadog** [comment] 2022-11-04 14:34
@techknowlogick  What's the reason why he didn't merge successfully?

**Comment by techknowlogick** [comment] 2022-11-04 20:44
Thanks. I will close this issue as a duplicate of https://github.com/techknowlogick/xgo/issues/108, and the discussion can continue there :)

**Closed by techknowlogick** 2022-11-04 20:44 UTC
